### ISSUE TITLE
Om 47 breaks create-navigator

### ISSUE THREAD

**Issue by livtanong** [amorokh/om-navigate#2] opened 2017-04-02 07:33 UTC
Specifically, at this commit, navigator proxies don't render:
https://github.com/omcljs/om/commit/70b46d565bcc98c483a9de8d637250a4a2996ad6#diff-ee424e6559581b5b893371373a777e5e

```clj
(defn- create-navigator
  [routes factory]
  (let [queries   (into [] (extract-queries routes))
        navigator (factory (clj->js (transform-routes routes)))
        proxy     (create-navigator-proxy navigator)]
    (when (seq queries)
      ;; They don't render specifically if iquery is specified. So if I comment the line below, it renders. Of course, incorrectly because no data.
      (specify! proxy om/IQuery (query [this] queries)))
    proxy))
```

**Comment by amorokh** [comment] 2017-04-03 19:16
I could not reproduce this, neither for 1.0.0-alpha47 nor version 1.0.0-alpha48.

**Comment by amorokh** [comment] 2017-04-07 07:44
Since no more feedback has been provided, I'll close this isssue.

**Closed as completed by amorokh** 2017-04-07 07:44 UTC
